name: Update Stock Recommendations

on:
  schedule:
    # 每个交易日下午3:30运行 (UTC时间7:30，北京时间15:30)
    - cron: '0 10 * * *'
  
  # 允许手动触发
  workflow_dispatch:

jobs:
  update-stocks:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-
      
      - name: Install dependencies
        run: cargo build --release
      
      - name: Run stock recommendation tool
        run: cargo run --release
        
      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
      
      - name: Commit and push if changed
        run: |
          git add docs/data/stocks.json
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update stock recommendations for $(date +'%Y-%m-%d')" && git push)
        env:
          # 使用GitHub提供的token
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

permissions:
  contents: write